spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpaboard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  messages:
    basename: messages, errors

  data:
    web:
      pageable:
        default-page-size: 12


server:
  port: 3030
  error:
    whitelabel:
      enabled: false

  servlet:
    session:
      timeout: 1800

logging:
  level:
    org.hibernate.SQL: debug
